// config/games.ts
export interface GameConfig {
  id: number;
  name: string;
  url?: string;           // Only for external games
  category: string;
  rating: string;
  plays: string;
  emoji: string;
  color: string;
  description: string;
  featured?: boolean;
  featuredTag?: string;
  type: 'builtin' | 'external';
}

export const GAMES: GameConfig[] = [
  // ── BUILT-IN GAMES (run natively inside Troy OS, always work) ──────
  {
    id: 1001,
    name: 'Snake',
    category: 'Arcade',
    rating: '4.5',
    plays: '∞',
    emoji: '🐍',
    color: '#10b981',
    description: 'Classic snake — arrow keys or tap to control',
    type: 'builtin',
    featured: true,
    featuredTag: 'Built-in',
  },
  {
    id: 1002,
    name: '2048',
    category: 'Puzzle',
    rating: '4.7',
    plays: '∞',
    emoji: '🔢',
    color: '#f59e0b',
    description: 'Merge tiles to reach 2048 — arrow keys to slide',
    type: 'builtin',
    featured: true,
    featuredTag: 'Built-in',
  },
  {
    id: 1003,
    name: 'Memory Match',
    category: 'Puzzle',
    rating: '4.6',
    plays: '∞',
    emoji: '🃏',
    color: '#8b5cf6',
    description: 'Flip cards and find matching pairs',
    type: 'builtin',
  },
  {
    id: 1004,
    name: 'Tic Tac Toe',
    category: 'Strategy',
    rating: '4.3',
    plays: '∞',
    emoji: '⭕',
    color: '#3b82f6',
    description: 'Classic X vs O — two player on one keyboard',
    type: 'builtin',
  },

  // ── EXTERNAL GAMES ─────────────────────────────────────────────────
  {
    id: 1,
    name: 'Troy Cloud',
    url: 'https://www.raccoongame.com/',
    category: 'Adventure',
    rating: '4.8',
    plays: '2.4M',
    emoji: '🦝',
    color: '#f59e0b',
    description: 'Explore the world as a crafty raccoon',
    type: 'external',
    featured: true,
    featuredTag: 'Top Pick',
  },
  {
    id: 2,
    name: 'Slope',
    url: 'https://watchdocumentaries.com/wp-content/uploads/games/slope/',
    category: 'Arcade',
    rating: '4.6',
    plays: '15M',
    emoji: '🎿',
    color: '#ef4444',
    description: 'Race a ball down an endless slope — dodge obstacles',
    type: 'external',
    featured: true,
    featuredTag: 'Popular',
  },
  {
    id: 3,
    name: 'Cookie Clicker',
    url: 'https://orteil.dashnet.org/cookieclicker/',
    category: 'Idle',
    rating: '4.8',
    plays: '50M',
    emoji: '🍪',
    color: '#d97706',
    description: 'Click cookies, build an empire — the classic idle game',
    type: 'external',
    featured: true,
    featuredTag: 'Classic',
  },
  {
    id: 4,
    name: 'Slither.io',
    url: 'https://slither.io/',
    category: 'Multiplayer',
    rating: '4.5',
    plays: '30M',
    emoji: '🐛',
    color: '#84cc16',
    description: 'Massive multiplayer snake — eat and grow, avoid others',
    type: 'external',
  },
  {
    id: 5,
    name: 'Agar.io',
    url: 'https://agar.io',
    category: 'Multiplayer',
    rating: '4.4',
    plays: '40M',
    emoji: '🔵',
    color: '#22d3ee',
    description: 'Grow your cell by eating others in this multiplayer classic',
    type: 'external',
  },
  {
    id: 6,
    name: 'Diep.io',
    url: 'https://diep.io/',
    category: 'Multiplayer',
    rating: '4.5',
    plays: '20M',
    emoji: '🔫',
    color: '#3b82f6',
    description: 'Tank shooter — upgrade your tank and battle others',
    type: 'external',
  },
  {
    id: 7,
    name: 'Krunker',
    url: 'https://krunker.io',
    category: 'Shooter',
    rating: '4.7',
    plays: '25M',
    emoji: '🎯',
    color: '#f97316',
    description: 'Fast-paced browser FPS — no download needed',
    type: 'external',
    featured: true,
    featuredTag: 'Hot',
  },
  {
    id: 8,
    name: 'Shell Shockers',
    url: 'https://shellshock.io/',
    category: 'Shooter',
    rating: '4.6',
    plays: '18M',
    emoji: '🥚',
    color: '#fbbf24',
    description: 'Egg-based multiplayer shooter — crack your enemies',
    type: 'external',
  },
  {
    id: 9,
    name: 'Smash Karts',
    url: 'https://smashkarts.io/',
    category: 'Racing',
    rating: '4.7',
    plays: '12M',
    emoji: '🏎️',
    color: '#ec4899',
    description: 'Kart battle arena — pick up weapons and destroy rivals',
    type: 'external',
  },
  {
    id: 10,
    name: 'Wordle',
    url: 'https://wordlegame.org/',
    category: 'Word',
    rating: '4.7',
    plays: '10M',
    emoji: '🔤',
    color: '#06b6d4',
    description: 'Guess the 5-letter word — 6 tries per day',
    type: 'external',
  },
  {
    id: 11,
    name: 'Connections',
    url: 'https://www.nytimes.com/games/connections',
    category: 'Word',
    rating: '4.6',
    plays: '8M',
    emoji: '🔗',
    color: '#a78bfa',
    description: 'Group words into categories — NYT daily puzzle',
    type: 'external',
  },
  {
    id: 12,
    name: 'skribbl.io',
    url: 'https://skribbl.io/',
    category: 'Multiplayer',
    rating: '4.8',
    plays: '22M',
    emoji: '🎨',
    color: '#f43f5e',
    description: 'Draw and guess with friends — online Pictionary',
    type: 'external',
  },
  {
    id: 13,
    name: 'Chess.com',
    url: 'https://chess.com',
    category: 'Strategy',
    rating: '4.9',
    plays: '50M',
    emoji: '♟️',
    color: '#22c55e',
    description: 'Play chess online or vs AI — the world\'s top chess site',
    type: 'external',
  },
  {
    id: 14,
    name: 'Minecraft Classic',
    url: 'https://classic.minecraft.net',
    category: 'Sandbox',
    rating: '4.8',
    plays: '35M',
    emoji: '⛏️',
    color: '#78716c',
    description: 'The original browser Minecraft — build anything',
    type: 'external',
  },
  {
    id: 15,
    name: 'bloxd.io',
    url: 'https://bloxd.io',
    category: 'Sandbox',
    rating: '4.5',
    plays: '10M',
    emoji: '🧱',
    color: '#16a34a',
    description: 'Minecraft-style multiplayer block game in the browser',
    type: 'external',
  },
  {
    id: 16,
    name: 'Run 3',
    url: 'https://www.coolmathgames.com/0-run-3/play',
    category: 'Arcade',
    rating: '4.7',
    plays: '28M',
    emoji: '🏃',
    color: '#7c3aed',
    description: 'Run through space tunnels — avoid falling into the void',
    type: 'external',
  },
  {
    id: 17,
    name: 'Tunnel Rush',
    url: 'https://5dd2e8e4-015f-11ea-ad56-9cb6d0d995f7.poki-gdn.com/5627efae-e960-407d-82a5-3da708eb4e68/index.html',
    category: 'Arcade',
    rating: '4.5',
    plays: '14M',
    emoji: '🌀',
    color: '#e11d48',
    description: 'Speed through a neon tunnel — reflexes required',
    type: 'external',
  },
  {
    id: 18,
    name: 'Happy Wheels',
    url: 'https://files.crazygames.com/ruffle/happywheels.html',
    category: 'Physics',
    rating: '4.6',
    plays: '20M',
    emoji: '🚲',
    color: '#dc2626',
    description: 'Ragdoll physics mayhem — survive brutal obstacle courses',
    type: 'external',
  },
  {
    id: 19,
    name: 'Drift Hunters',
    url: 'https://webglmath.github.io/drift-hunters/',
    category: 'Racing',
    rating: '4.7',
    plays: '16M',
    emoji: '🚗',
    color: '#0ea5e9',
    description: 'Realistic drift racing — tune your car and hit the track',
    type: 'external',
  },
  {
    id: 20,
    name: 'Moto X3M',
    url: 'https://html5.gamedistribution.com/rvvASMiM/5b0abd4c0faa4f5eb190a9a16d5a1b4c/index.html',
    category: 'Racing',
    rating: '4.6',
    plays: '18M',
    emoji: '🏍️',
    color: '#f97316',
    description: 'Extreme motorbike stunts — conquer wild obstacle tracks',
    type: 'external',
  },
  {
    id: 21,
    name: 'Retro Bowl',
    url: '/e/2/retro/index.html',
    category: 'Sports',
    rating: '4.8',
    plays: '9M',
    emoji: '🏈',
    color: '#b45309',
    description: 'Retro-style American football management game',
    type: 'external',
  },
  {
    id: 22,
    name: 'Basketball Stars',
    url: 'https://html5.gamedistribution.com/69d78d071f704fa183d75b4114ae40ec/',
    category: 'Sports',
    rating: '4.5',
    plays: '11M',
    emoji: '🏀',
    color: '#ea580c',
    description: '1v1 basketball — dribble, shoot, and dunk on opponents',
    type: 'external',
  },
  {
    id: 23,
    name: 'Fireboy & Watergirl',
    url: 'https://www.coolmathgames.com/sites/default/files/public_games/40034/',
    category: 'Puzzle',
    rating: '4.7',
    plays: '30M',
    emoji: '🔥',
    color: '#f97316',
    description: 'Co-op puzzle platformer — team up to reach the exit',
    type: 'external',
  },
  {
    id: 24,
    name: 'Papa\'s Burgeria',
    url: 'https://www.coolmathgames.com/0-papas-burgeria/play',
    category: 'Casual',
    rating: '4.6',
    plays: '13M',
    emoji: '🍔',
    color: '#d97706',
    description: 'Build perfect burgers for impatient customers',
    type: 'external',
  },
  {
    id: 25,
    name: 'Friday Night Funkin\'',
    url: 'https://w8.snokido.com/games/html5/friday-night-funkin/0281/index.html',
    category: 'Rhythm',
    rating: '4.7',
    plays: '20M',
    emoji: '🎵',
    color: '#9333ea',
    description: 'Rhythm battle game — hit the arrows to the beat',
    type: 'external',
  },
  {
    id: 26,
    name: 'Voxiom.io',
    url: 'https://voxiom.io/',
    category: 'Shooter',
    rating: '4.5',
    plays: '7M',
    emoji: '💣',
    color: '#64748b',
    description: 'Voxel battle royale — mine, build, and fight to win',
    type: 'external',
  },
  {
    id: 27,
    name: 'Tetr.io',
    url: 'https://tetr.io/',
    category: 'Puzzle',
    rating: '4.8',
    plays: '8M',
    emoji: '🟦',
    color: '#2563eb',
    description: 'Competitive multiplayer Tetris — blazing fast',
    type: 'external',
  },
  {
    id: 28,
    name: 'Gartic Phone',
    url: 'https://garticphone.com',
    category: 'Multiplayer',
    rating: '4.9',
    plays: '15M',
    emoji: '📞',
    color: '#10b981',
    description: 'Telephone pictionary with friends — hilarious results guaranteed',
    type: 'external',
  },
  {
    id: 29,
    name: '1v1.LOL',
    url: 'https://1v1.lol',
    category: 'Shooter',
    rating: '4.5',
    plays: '19M',
    emoji: '🏗️',
    color: '#ef4444',
    description: 'Build and battle — Fortnite-style 1v1 browser game',
    type: 'external',
  },
  {
    id: 30,
    name: 'Snow Rider 3D',
    url: 'https://html5.gamedistribution.com/rvvASMiM/3b79a8537ebc414fb4f9672a9b8c68c8/index.html',
    category: 'Racing',
    rating: '4.5',
    plays: '6M',
    emoji: '🛷',
    color: '#93c5fd',
    description: 'Sled down snowy slopes — dodge trees and collect gifts',
    type: 'external',
  },
  {
    id: 31,
    name: 'Narrow One',
    url: 'https://narrow.one',
    category: 'Shooter',
    rating: '4.7',
    plays: '8M',
    emoji: '🏹',
    color: '#6b7280',
    description: 'Medieval team-based bow-and-arrow shooter',
    type: 'external',
  },
  {
    id: 32,
    name: 'Buckshot Roulette',
    url: 'https://buckshotroulette.online/game/v11/',
    category: 'Strategy',
    rating: '4.6',
    plays: '4M',
    emoji: '🎲',
    color: '#1c1917',
    description: 'High-stakes shotgun roulette — outsmart your opponent',
    type: 'external',
  },
  {
    id: 33,
    name: 'Time Shooter 2',
    url: 'https://html5.gamedistribution.com/62a72f2da7cb4b609579a47653546e6a/',
    category: 'Shooter',
    rating: '4.7',
    plays: '5M',
    emoji: '⏱️',
    color: '#0891b2',
    description: 'Time moves only when you move — plan every shot',
    type: 'external',
  },
  {
    id: 34,
    name: 'Rocket Bot Royale',
    url: 'https://rocketbotroyale2.winterpixel.io/',
    category: 'Shooter',
    rating: '4.6',
    plays: '5M',
    emoji: '🚀',
    color: '#7c3aed',
    description: 'Tank battle royale — last bot standing wins',
    type: 'external',
  },
  {
    id: 35,
    name: 'Territorial.io',
    url: 'https://territorial.io',
    category: 'Strategy',
    rating: '4.6',
    plays: '6M',
    emoji: '🗺️',
    color: '#16a34a',
    description: 'Claim territory and conquer the map in real time',
    type: 'external',
  },
  {
    id: 36,
    name: 'Neal.fun',
    url: 'https://neal.fun',
    category: 'Casual',
    rating: '4.8',
    plays: '9M',
    emoji: '🎮',
    color: '#8b5cf6',
    description: 'Collection of weird and wonderful interactive experiences',
    type: 'external',
  },
  {
    id: 37,
    name: 'Geforce NOW',
    url: 'https://play.geforcenow.com',
    category: 'Cloud',
    rating: '4.7',
    plays: '5M',
    emoji: '☁️',
    color: '#16a34a',
    description: 'Stream full PC games in your browser via Nvidia\'s cloud',
    type: 'external',
    featured: true,
    featuredTag: 'Cloud Gaming',
  },
  {
    id: 38,
    name: 'Newgrounds',
    url: 'https://newgrounds.com/',
    category: 'Arcade',
    rating: '4.5',
    plays: '20M',
    emoji: '🅰️',
    color: '#f97316',
    description: 'Thousands of free Flash-era games and animations',
    type: 'external',
  },
  {
    id: 39,
    name: 'Pokemon Showdown',
    url: 'https://play.pokemonshowdown.com',
    category: 'Strategy',
    rating: '4.8',
    plays: '10M',
    emoji: '⚡',
    color: '#facc15',
    description: 'Competitive Pokémon battles — no cartridge needed',
    type: 'external',
  },
  {
    id: 40,
    name: 'Tiny Fishing',
    url: 'https://www.dob5.com/d/file/games/tiny-fishing/',
    category: 'Casual',
    rating: '4.4',
    plays: '7M',
    emoji: '🎣',
    color: '#0369a1',
    description: 'Chill fishing idle game — cast deeper, catch rarer fish',
    type: 'external',
  },
];